### ISSUE TITLE
bug/kakao implementation error

### ISSUE THREAD

**Issue by jiwonHub** [jiwonHub/RunningMan#10]
카카오 로그인 라이브러리 추가가 오류남.
implementation 'com.kakao.sdk:v2-all:2.20.1'
버전이 이상한건지 이 코드를 추가하기만 하면 에러가 자꾸나서 추가 할 수가 없음. 
뭐가 문제인지 확인 필요함

**Comment by centerfoward** [comment]
implementation ("com.kakao.sdk:v2-all:2.20.1")
으로도 해봤는지?

**Comment by jiwonHub** [comment]
카카오 공식 문서에 있던 코드 그대로 복사해온 터라 이슈엔 저렇게 달려있지만 
실제 코드에서는 centerforward님과 같이 괄호로 감싸서 라이브러리를 추가했었습니다
